<?php

namespace App\Enums;

enum RegimeBens: string
{
    case COMUNHAO_PARCIAL = 'COMUNHAO_PARCIAL';
    case COMUNHAO_UNIVERSAL = 'COMUNHAO_UNIVERSAL';
    case SEPARACAO_TOTAL = 'SEPARACAO_TOTAL';
    case PARTICIPACAO_FINAL_AQUESTOS = 'PARTICIPACAO_FINAL_AQUESTOS';
}
