<?php

namespace App\Enums;

enum TipoDocumento: string
{
    case CONTRATO_ASSINADO = 'CONTRATO_ASSINADO';
    case COMPROVANTE_PAGAMENTO = 'COMPROVANTE_PAGAMENTO';
    case LAUDO_VISTORIA = 'LAUDO_VISTORIA';
    case RG_CPF = 'RG_CPF';
    case COMPROVANTE_RESIDENCIA = 'COMPROVANTE_RESIDENCIA';
    case COMPROVANTE_RENDA = 'COMPROVANTE_RENDA';
    case FOTO_IMOVEL = 'FOTO_IMOVEL';
    case APOLICE_SEGURO = 'APOLICE_SEGURO';
    case OUTRO = 'OUTRO';
}
